Algoritmo "contador de 0 a 10 -EXE 01"
//
//
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 05/01/2024
Var
   // Seção de Declarações das variáveis
   contador: inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   contador <- 0
   Enquanto (contador <=10) faca
      Escreval(contador)
      contador <- contador + 1
   FimEnquanto
   Escreval("Terminei de contar")

Fimalgoritmo

