Algoritmo "contador de 10 a 0 - Exe 02"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 08/01/2024
Var
// Seção de Declarações das variáveis 
  contador: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
    contador <- 10
    Enquanto (contador >= 0) faca
    Escreval (contador)
    contador <- contador - 1
    FimEnquanto
    Escreval("Terminei de contar")

Fimalgoritmo