Algoritmo "primeiro"
//  
//  
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 29/11/2023
Var
// Seção de Declarações das variáveis 
       msg:caractere
       msge:caractere

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
     msg <- " Olá, Mundo!"
     Escreval("Mensagem ", msg)
     msg <- "Me livrei da maldição!"
     Escreval("Mensagem " , msg )

Fimalgoritmo