Algoritmo "Numeros"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 29/11/2023
Var
// Seção de Declarações das variáveis 
     A: Real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
       // A <- RAIZQ(81)
       // Escreva(A)
         //A <- Int(RAIZQ (90))
         //A <- Abs(-50)
         A <- Sen(GraupRad(90))
         Escreva(A)

Fimalgoritmo