Algoritmo "contador 02 - Exe 06"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 09/01/2024
Var
// Seção de Declarações das variáveis 
  contador: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   contador <- 1
   Repita
   Escreval(contador)
   contador <- contador + 1
   Ate (contador > 10)

Fimalgoritmo