Algoritmo "ValoresPares - EXE 03"
//
//
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 12/01/2024
Var
   // Seção de Declarações das variáveis
   Contador, Valor: Inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   Escreva("Digite um valor: ")
   Leia(Valor)
   Para Contador <- 0 ate Valor passo 2 faca
      Escreval(Contador)
   FimPara

Fimalgoritmo